export const SHOW_ERROR = 'SHOW_ERROR';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const CONNECTION_SUCCEEDED = 'CONNECTION_SUCCEEDED';
export const COULD_ACCESS_ACCOUNT = 'COULD_ACCESS_ACCOUNT';
export const COULD_NOT_ACCESS_ACCOUNT = 'COULD_NOT_ACCESS_ACCOUNT';

export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT';
export const RECEIVE_ETHER_BALANCE = 'RECEIVE_ETHER_BALANCE';
export const RECEIVE_TOKEN_BALANCE = 'RECEIVE_TOKEN_BALANCE';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const RECEIVE_TRANSACTION = 'RECEIVE_TRANSACTION';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const RECEIVE_LAST_TRANSACTION = 'RECEIVE_LAST_TRANSACTION';

export const RECEIVE_TOKEN_SALE = 'RECEIVE_TOKEN_SALE';
export const RECEIVE_TOKEN_PURCHASE = 'RECEIVE_TOKEN_PURCHASE';

export const START_SEARCHING = 'START_SEARCHING';
export const SEARCH_NOT_FOUND = 'SEARCH_NOT_FOUND';
export const SEARCH_FOUND_TOKEN_SALE = 'SEARCH_FOUND_TOKEN_SALE';
export const SEARCH_FOUND_TOKEN_PURCHASE = 'SEARCH_FOUND_TOKEN_PURCHASE';
